#!/usr/bin/env bash
# configuring an Nginx server to listen on port 80

# Removing default config file
rm /etc/nginx/sites-enabled/default
# configuring an Nginx server to listen on port 80 for all active IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restarting Nginx
service nginx restart
