#!/usr/bin/env bash
# Creating a symbolic link between nginx config file(s)
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
~                            
